version: '3'
#This file is used in tests. It can also be used if you want to develop on localhost with local keycloak and database.
services:
  # mysql database
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: time
    ports:
      - 3306:3306
