apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-deployment
  labels:
    app: time
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time
  template:
    metadata:
      labels:
        app: time
    spec:
      containers:
        - name: time
          image: docker.io/library/time-container:0.0.2
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: time-service
spec:
  type: NodePort
  selector:
    app: time
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 31111
